/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.soura.chatapp.ChatApp;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ChatApp classUnderTest = new ChatApp();
//        assertNotNull(classUnderTest(), "app should have a greeting");
    }
}
